
services:
  app:
    image: streamlit-frontend:frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/src:/app
  task-service:
    image: task-service:latest
    ports:
      - "5000:5000"
    volumes:
      - ./task-service/src:/app
  postgres:
    image: postgres-db:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres

volumes:
  postgres-data:
