apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: zeda21/assignment-build-something:task-service
        ports:
        - containerPort: 5000
        command: ["uvicorn", "task_service:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort

